# Build settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site settings
title: 2014年厦门 GDG Devfest 大会官方网站
email: gdgxiamen@gmail.com
description: "厦门GDG Devfest 2014 Season官方网站，所有关于本会议的信息均在此做最新更新。"
baseurl: "/devfest2014"
url: "http://devfest.gdgxiamen.org"
permalink: /blog/:title
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""

# Location block
eventLocationName: "厦门华侨大厦（大酒店）"
eventLocationAddress: "厦门市新华路70-74号"
eventStartTime: "2014-10-25T10:00"
eventStartTimeHumanReadable: "10:00"
eventEndTime: "2014-10-25T17:00"
eventEndTimeHumanReadable: "17:00"
eventPlaceCoordinates: "24.455429, 118.085909"
mapCenterCoordinates: "24.455429, 118.085909"
mapMobileCenterCoordinates: "24.455429, 118.085909"

# Logistics Location Block
logisticsMapCenterCoordinates: "24.455429, 118.085909"
logisticsMapMobileCenterCoordinates: "24.455429, 118.085909"

#Tweets feed
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Subscribe
subscribeAction: "http://gdgxiamen.us7.list-manage.com/subscribe/post?u=a42cb83b687823026c1a7acaf&amp;id=3c5dcb7fca"

# Documents
c4pUrl: "https://gdgdocs.org/r/jkSjwW"
c4sponsorsUrl: "/assets/GDG_Xiamen_DevFest_Partnership.pdf"

# Head
metaKeywords: "GDG,厦门 GDG,开发者大会,event, gdg, devfest, google, programming, android, chrome, developers"
twitterAccount: "@GDGXiamen"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Header
eventDate: "2014年10月25日"
typeoutTextValues: ' "", "Season", "China","Xiamen" '

# About Event Block
eventName: "GDG DevFest (Google 开发者大会)"

# Team Block
aboutUs: "仅从技术上讲，Google 已然是引领全球技术创新的代名词，其产品（Google+ 除外）也正在改变无数人的生活，一些非常创新且意想不到的项目，都被这些顶尖的开发者所创造，无数的创业公司、中小公司、大型企业通过 Google 开放的生态环境成功的建立起属于他们的商业帝国，这也是我们，为什么坚定的通过 Google 的技术进行创新，并坚持把这些技术分享给更多的人的原因。<br />全世界范围内，越来越多的开发者开始讨论并使用 Google 的技术进行创新，所以就有了自发组织的谷歌开发者社区，令人兴奋的是，Google 官方在各个方面给社区以最大的支持，所以，请支持先进技术的发展，支持谷歌开发者社区，谢谢！<br />——郑灵翔, 厦门 GDG 创始人。"

# Speakers List Block
showSessions: true
thumbnailsFolder: /img/speakers/

# Footer
gplusFollowUsUrl: "https://www.google.com/+GDGXiamenOrgCN"
twitterFollowUsUrl: "#"
fbFollowUsUrl: ""

# Blog
blogCommentsEnabled: true
discusShortName: false
duoshuoShortName: "devfest"
duoshuoDev: true

# Static Files
JSjQueryURL: "//dn-staticfile.qbox.me/jquery/2.1.1/jquery.min.js"
JSBootstrapURL: "//dn-staticfile.qbox.me/twitter-bootstrap/3.2.0/js/bootstrap.min.js"
CSSBootstrapURL: "//dn-staticfile.qbox.me/twitter-bootstrap/3.2.0/css/bootstrap.min.css"

# Google Service Domains
GMapAPIDomain: "http://maps.api.gdgdocs.org/"
GFontsDomain: "https://fonts.lug.ustc.edu.cn"
